### ISSUE TITLE
Useful to have sorting capabilities for comparisons to be made

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policieslist#7]
Users would like sorting capabilities to be able to compare countries. Some possibilities are: 
1. Is it an accessibility policy, vs non-discrimination policy, vs procurement policy, etc.? 
2. Does it apply to web only or is it broader? 
3. Does it reference WCAG directly or through another mechanism (e.g. Copy &paste)? 
4. Does it use WCAG as-is, or some derivative of WCAG? 1.0 vs 2.0? How to handle generic references to WCAG or WAI?

**Comment by yatil** [comment]
This issue was moved to w3c/wai-policies-prototype#298
